#include <stdbool.h>
#include <stdint.h>


#include <stdio.h>
#include <unistd.h>

// ---- BEGIN of source automatically generated by Atom ----


static uint64_t __global_clock = 0;



static const uint32_t __coverage_len = 1;
static uint32_t __coverage[1] = {0};
static uint32_t __coverage_index = 0;
struct {  /* state */
  struct {  /* ex1 */
    struct {  /* ex1 */
      bool b;
    } ex1;
  } ex1;
} state =
{  /* state */
  {  /* ex1 */
    {  /* ex1 */
      /* b */  false
    }
  }
};

/* Rule { 0, ex1.ex1 } */
static void __r0() {
  bool __0 = true;
  if (__0) {
    __coverage[0] = __coverage[0] | (1 << 0);
  }
  state.ex1.ex1.b = __0;
}


static void __assertion_checks() {
}


void ex1()
{

  {
    static uint8_t __scheduling_clock = 0;
    if (__scheduling_clock == 0) {
      __assertion_checks(); __r0();  /* Rule { 0, ex1.ex1 } */
      __scheduling_clock = 0;
    }
    else {
      __scheduling_clock = __scheduling_clock - 1;
    }
  }

  __global_clock = __global_clock + 1;

}

// ---- END of source automatically generated by Atom ----

int main(int argc, char **argv) {
  while(1) { ex1(); usleep(500); }
}

