#include <stdbool.h>
#include <stdint.h>


#include <stdio.h>
#include <unistd.h>

// ---- BEGIN of source automatically generated by Atom ----


static uint64_t __global_clock = 0;



static const uint32_t __coverage_len = 1;
static uint32_t __coverage[1] = {0};
static uint32_t __coverage_index = 0;
struct {  /* state */
  struct {  /* ex3 */
    struct {  /* ex3 */
      bool __channel_ach;
      bool __channel_ach_ready;
      bool __channel_bch;
      bool __channel_bch_ready;
      struct {  /* alice */
        int8_t x;
      } alice;
      struct {  /* bob */
        int8_t x;
      } bob;
    } ex3;
  } ex3;
} state =
{  /* state */
  {  /* ex3 */
    {  /* ex3 */
      /* __channel_ach */  0,
      /* __channel_ach_ready */ 0,
      /* __channel_bch */  0,
      /* __channel_bch_ready */ 0,
      {  /* alice */
        /* x */  0
      },
      {  /* bob */
        /* x */  0
      }
    }
  }
};

/* Rule { 0, ex3.ex3.alice } */
static void __r0() {
  bool __0 = state.ex3.ex3.__channel_bch_ready;
  bool __1 = true;
  int8_t __2 = state.ex3.ex3.alice.x;
  int8_t __3 = 1;
  int8_t __4 = __2 + __3;
  int8_t __5 = __0 ? __4 : __2;
  if (__0 && __1) {
    __coverage[0] = __coverage[0] | (1 << 0);
    state.ex3.ex3.__channel_ach = __1;
    state.ex3.ex3.__channel_ach_ready = true;
    state.ex3.ex3.__channel_bch_ready = false;
    state.ex3.ex3.__channel_bch = 0;
  }
  state.ex3.ex3.alice.x = __5;
}

/* Rule { 1, ex3.ex3.bob } */
static void __r1() {
  bool __0 = state.ex3.ex3.__channel_ach_ready;
  bool __1 = true;
  int8_t __2 = state.ex3.ex3.bob.x;
  int8_t __3 = 1;
  int8_t __4 = __2 + __3;
  int8_t __5 = __0 ? __4 : __2;
  if (__0 && __1) {
    __coverage[0] = __coverage[0] | (1 << 1);
    state.ex3.ex3.__channel_bch = __1;
    state.ex3.ex3.__channel_bch_ready = true;
    state.ex3.ex3.__channel_ach_ready = false;
    state.ex3.ex3.__channel_ach = 0;
  }
  state.ex3.ex3.bob.x = __5;
}


static void __assertion_checks() {
}


void ex3()
{

  {
    static uint8_t __scheduling_clock = 0;
    if (__scheduling_clock == 0) {
      __assertion_checks(); __r0();  /* Rule { 0, ex3.ex3.alice } */
      __assertion_checks(); __r1();  /* Rule { 1, ex3.ex3.bob } */
      __scheduling_clock = 0;
    }
    else {
      __scheduling_clock = __scheduling_clock - 1;
    }
  }

  __global_clock = __global_clock + 1;

}

// ---- END of source automatically generated by Atom ----

int main(int argc, char **argv) {
  while(1) { ex3(); usleep(500); }
}

