module Main (module Main) where

import Language.LIMA
import Language.LIMA.Graph
import Language.LIMA.C
import Language.Sally

import Periodic


main :: IO ()
main = do
  compileToC "ex1" ex1
  compileToSally "periodic_ex1" defaultCfg "periodic_ex1.mcmt" ex1 Nothing
  graphAtom "periodic_ex1" ex1

  compileToC "ex2" ex2
  compileToSally "periodic_ex2" defaultCfg "periodic_ex2.mcmt" ex2 Nothing
  graphAtom "periodic_ex2" ex2

  compileToC "ex3" ex3
  compileToSally "periodic_ex3" defaultCfg "periodic_ex3.mcmt" ex3 Nothing
  graphAtom "periodic_ex3" ex3



-- C Code Generator Utilities --------------------------------------------

-- | Invoke the atom compiler, generating 'om1.{c,h}'
-- Also print out info on the generated schedule.
compileToC :: Name -> Atom () -> IO ()
compileToC nm atm = do
  res <- compile nm cfg atm
  putStrLn $ reportSchedule (compSchedule res)
  where
    cfg = defaults { cCode = prePostCode nm }

-- | Custom pre-post code for generated C
prePostCode :: Name -> [Name] -> [Name] -> [(Name, Type)] -> (String, String)
prePostCode nm _ _ _ =
  ( unlines [ "#include <stdio.h>"
            , "#include <unistd.h>"
            , ""
            , "// ---- BEGIN of source automatically generated by Atom ----"
            ]
  , unlines [ "// ---- END of source automatically generated by Atom ----"
            , ""
            , "int main(int argc, char **argv) {"
            , "  while(1) { " ++ nm ++ "(); usleep(500); }"
            , "}"
            ]
  )
