module Main where

import Language.SLIM
import Language.SLIM.C
import Language.Sally

import SLIMWBS (wbs)

main :: IO ()
main = do
  putStrLn "Compiling WBS to C... (wbs.{c,h})"
  compileWBSToC

  putStrLn "Compiling WBS to Sally... (wbs.mcmt)"
  let sallyCfg = defaultCfg { cfgMFA = hybridMFA }
  compileToSally "wbs" sallyCfg "wbs.mcmt" wbs Nothing

  putStrLn "Done."


-- C Code Generator ------------------------------------------------------

-- | Invoke the SLIM compiler, generating 'wbs.{c,h}'
-- Also print out info on the generated schedule.
compileWBSToC :: IO ()
compileWBSToC = do
  res <- compile "wbs" cfg wbs
  putStrLn $ reportSchedule (compSchedule res)
  where
    cfg = defaults { cCode = prePostCode }

-- | Custom pre-post code for generated C
prePostCode :: [Name] -> [Name] -> [(Name, Type)] -> (String, String)
prePostCode _ _ _ =
  ( unlines [ "#include <stdio.h>"
            , "#include <unistd.h>"
            , ""
            , "// ---- BEGIN of source automatically generated by SLIM ----"
            ]
  , unlines [ "// ---- END of source automatically generated by SLIM ----"
            , ""
            , "int main(int argc, char **argv) {"
            , "  while(1) { om1(); usleep(500); }"
            , "}"
            ]
  )
