module Main (module Main) where

import Language.LIMA
import Language.LIMA.Graph
import Language.LIMA.C
import Language.Sally

import SMP

main :: IO ()
main = do
  compileToC "smp" smp
  compileToSally "smp" defaultCfg "smp.mcmt" smp Nothing


-- C Code Generator Utilities --------------------------------------------

-- | Invoke the atom compiler, generating 'om1.{c,h}'
-- Also print out info on the generated schedule.
compileToC :: Name -> Atom () -> IO ()
compileToC nm atm = do
  res <- compile nm cfg atm
  putStrLn $ reportSchedule (compSchedule res)
  where
    cfg = defaults { cCode = prePostCode nm }

-- | Custom pre-post code for generated C
prePostCode :: Name -> [Name] -> [Name] -> [(Name, Type)] -> (String, String)
prePostCode nm _ _ _ =
  ( unlines [ "#include <stdio.h>"
            , "#include <unistd.h>"
            , ""
            , "// ---- BEGIN of source automatically generated by Atom ----"
            ]
  , unlines [ "// ---- END of source automatically generated by Atom ----"
            , ""
            , "int main(int argc, char **argv) {"
            , "  while(1) { " ++ nm ++ "(); usleep(500); }"
            , "}"
            ]
  )
